//Lucas Raphael, 2525518 - Mateus Rodrigues, 2503700 - Norberto Junior, 2209136

import javax.swing.JOptionPane;

/**
 *
 * @author Mateus
 */
public class FormPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrincipal.class.getName());

    //MÉTODO SINGLETON
    private static FormPrincipal formPrincipalUnico;

    private FormPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static FormPrincipal geraFormPrincipal() {
        if (formPrincipalUnico == null) {
            formPrincipalUnico = new FormPrincipal();
        }
        return formPrincipalUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtBemVindo = new javax.swing.JLabel();
        rtBemDeposito = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        barMnPrinc = new javax.swing.JMenu();
        itMnIniProg = new javax.swing.JMenuItem();
        itMnSairProg = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtBemVindo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rtBemVindo.setText("Bem Vindo ao Sistema");

        rtBemDeposito.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        rtBemDeposito.setText("Depósito do Zé");

        barMnPrinc.setText("Sistema");

        itMnIniProg.setText("Iniciar");
        itMnIniProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnIniProgActionPerformed(evt);
            }
        });
        barMnPrinc.add(itMnIniProg);

        itMnSairProg.setText("Sair");
        itMnSairProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnSairProgActionPerformed(evt);
            }
        });
        barMnPrinc.add(itMnSairProg);

        jMenuBar1.add(barMnPrinc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rtBemVindo)
                    .addComponent(rtBemDeposito))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(rtBemVindo)
                .addGap(18, 18, 18)
                .addComponent(rtBemDeposito)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMnIniProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnIniProgActionPerformed
        FormHome.geraFormHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itMnIniProgActionPerformed

    private void itMnSairProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnSairProgActionPerformed
        sairPrograma();
    }//GEN-LAST:event_itMnSairProgActionPerformed

    public void sairPrograma() {
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair do sistema?",
                "Confirmação de Saída",
                JOptionPane.YES_NO_OPTION
        );
        if (resp == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> FormPrincipal.geraFormPrincipal().setVisible(true)); // Usa o Singleton para exibir
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu barMnPrinc;
    private javax.swing.JMenuItem itMnIniProg;
    private javax.swing.JMenuItem itMnSairProg;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel rtBemDeposito;
    private javax.swing.JLabel rtBemVindo;
    // End of variables declaration//GEN-END:variables
}
