//Lucas Raphael, 2525518 - Mateus Rodrigues, 2503700 - Norberto Junior, 2209136

import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.util.logging.Logger;

/**
 *
 * @author Mateus
 */
public class FormAtualizarQuantEstoque extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(FormAtualizarQuantEstoque.class.getName());

    //MÉTODO SINGLETON
    private static FormAtualizarQuantEstoque formAtualizarQuantidadeUnico;

    private BDEstoque bdEstoque = BDEstoque.geraBDEstoque();

    private FormAtualizarQuantEstoque() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Depósito do Zé - Atualizar Quantidade de Estoque");
    }
    
    //MÉTODO SINGLETON
    public static FormAtualizarQuantEstoque geraFormAtualizarQuantEstoque() {
        if (formAtualizarQuantidadeUnico == null) {
            formAtualizarQuantidadeUnico = new FormAtualizarQuantEstoque();
        }
        return formAtualizarQuantidadeUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtAtuEstoque = new javax.swing.JLabel();
        rtCod = new javax.swing.JLabel();
        rtNovaQuant = new javax.swing.JLabel();
        cxCod = new javax.swing.JTextField();
        cxNovaQuant = new javax.swing.JTextField();
        btAtualizar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtAtuEstoque.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rtAtuEstoque.setText("Atualizar Estoque");

        rtCod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtCod.setText("Código");

        rtNovaQuant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtNovaQuant.setText("Nova Quantidade");

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btAtualizar)
                            .addGap(58, 58, 58)
                            .addComponent(btSair))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rtCod)
                                .addComponent(rtNovaQuant))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cxCod, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cxNovaQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(rtAtuEstoque))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(rtAtuEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCod)
                    .addComponent(cxCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNovaQuant)
                    .addComponent(cxNovaQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAtualizar)
                    .addComponent(btSair))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sairForm();
    }//GEN-LAST:event_btSairActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        atualizarQuantidade();
    }//GEN-LAST:event_btAtualizarActionPerformed

    public void atualizarQuantidade() {
        try {
            if (cxCod.getText().isEmpty() || cxNovaQuant.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, preencha o Código do Material e a Nova Quantidade.", "Campos Vazios", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int codigo = Integer.parseInt(cxCod.getText());
            int novaQuantidade = Integer.parseInt(cxNovaQuant.getText());

            MateriaisModel materialAtualizado = bdEstoque.atualizaQuantidadeMaterial(codigo, novaQuantidade);

            if (materialAtualizado != null) {
                JOptionPane.showMessageDialog(this, 
                    "Quantidade do material '" + materialAtualizado.getNome() + "' atualizada para " + materialAtualizado.getQuantidade() + ".",
                    "Atualização de Quantidade", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Material não encontrado ou erro na atualização. Verifique o código.", "Erro de Atualização", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Erro: Código e Nova Quantidade devem ser números inteiros.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Erro inesperado ao atualizar quantidade", e);
            JOptionPane.showMessageDialog(this, "Ocorreu um erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void limparCampos() {
        cxCod.setText("");
        cxNovaQuant.setText("");
        cxCod.requestFocus();
    }

    public void sairForm() {
        int resp = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente fechar a janela de atualização de quantidade?",
                "Saída",
                JOptionPane.YES_NO_OPTION
        );
        if (resp == JOptionPane.YES_OPTION) {
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCod;
    private javax.swing.JTextField cxNovaQuant;
    private javax.swing.JLabel rtAtuEstoque;
    private javax.swing.JLabel rtCod;
    private javax.swing.JLabel rtNovaQuant;
    // End of variables declaration//GEN-END:variables
}
