//Lucas Raphael, 2525518 - Mateus Rodrigues, 2503700 - Norberto Junior, 2209136

import javax.swing.JOptionPane;
import java.util.logging.Logger;

/**
 *
 * @author Mateus
 */
public class FormRemoverMaterial extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(FormRemoverMaterial.class.getName());

    //MÉTODO SINGLETON
    private static FormRemoverMaterial formRemoverMaterialUnico;

    private BDEstoque bdEstoque = BDEstoque.geraBDEstoque();

    private FormRemoverMaterial() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Depósito do Zé - Remover Material do Estoque");
    }

    //MÉTODO SINGLETON
    public static FormRemoverMaterial geraFormRemoverMaterial() {
        if (formRemoverMaterialUnico == null) {
            formRemoverMaterialUnico = new FormRemoverMaterial();
        }
        return formRemoverMaterialUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSair = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        rtRemovMat = new javax.swing.JLabel();
        rtCod = new javax.swing.JLabel();
        cxCod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        rtRemovMat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rtRemovMat.setText("Remover Material");

        rtCod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtCod.setText("Código");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btRemover)
                        .addGap(55, 55, 55)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtCod)
                        .addGap(18, 18, 18)
                        .addComponent(cxCod, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rtRemovMat))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(rtRemovMat)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCod)
                    .addComponent(cxCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btRemover))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        removerMaterial();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sairForm();
    }//GEN-LAST:event_btSairActionPerformed

public void removerMaterial() {
        try {
            if (cxCod.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, digite o Código do Material para remover.", "Campo Vazio", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int codigo = Integer.parseInt(cxCod.getText());

            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Tem certeza que deseja remover o material com Código: " + codigo + "?",
                    "Confirmação de Remoção",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                MateriaisModel materialRemovido = bdEstoque.excluiMaterial(codigo);

                if (materialRemovido != null) {
                    JOptionPane.showMessageDialog(this, 
                        "Material '" + materialRemovido.getNome() + "' removido com sucesso.",
                        "Remoção de Material", JOptionPane.INFORMATION_MESSAGE);
                    limparCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Material não encontrado. Verifique o código.", "Erro de Remoção", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Erro: O Código deve ser um número inteiro.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Erro inesperado ao remover material", e);
            JOptionPane.showMessageDialog(this, "Ocorreu um erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void limparCampos() {
        cxCod.setText("");
        cxCod.requestFocus();
    }

    public void sairForm() {
        int resp = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente fechar a janela de remoção de material?",
                "Saída",
                JOptionPane.YES_NO_OPTION
        );
        if (resp == JOptionPane.YES_OPTION) {
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCod;
    private javax.swing.JLabel rtCod;
    private javax.swing.JLabel rtRemovMat;
    // End of variables declaration//GEN-END:variables
}
