//Lucas Raphael, 2525518 - Mateus Rodrigues, 2503700 - Norberto Junior, 2209136

import javax.swing.JOptionPane;

/**
 *
 * @author Mateus
 */
public class FormHome extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormHome.class.getName());

    //MÉTODO SINGLETON
    private static FormHome formHomeUnico;

    private FormHome() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static FormHome geraFormHome() {
        if (formHomeUnico == null) {
            formHomeUnico = new FormHome();
        }
        return formHomeUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtDepositoHome = new javax.swing.JLabel();
        btCadCliente = new javax.swing.JButton();
        btVenda = new javax.swing.JButton();
        barMnHome = new javax.swing.JMenuBar();
        mnHomeCad = new javax.swing.JMenu();
        itMnCadFun = new javax.swing.JMenuItem();
        itMnCadMat = new javax.swing.JMenu();
        itMnCadAlvenaria = new javax.swing.JMenuItem();
        itMnCadFerragens = new javax.swing.JMenuItem();
        itMnCadCarpintaria = new javax.swing.JMenuItem();
        mnHomeRelat = new javax.swing.JMenu();
        itMnListClient = new javax.swing.JMenuItem();
        itMnListFun = new javax.swing.JMenuItem();
        itMnListEstoque = new javax.swing.JMenuItem();
        itMnListVenda = new javax.swing.JMenuItem();
        mnHomeSist = new javax.swing.JMenu();
        itMnRemoProd = new javax.swing.JMenuItem();
        itMnAttQuant = new javax.swing.JMenuItem();
        itMnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtDepositoHome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        rtDepositoHome.setText("Depósito do Zé");

        btCadCliente.setText("Cadastrar Cliente");
        btCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadClienteActionPerformed(evt);
            }
        });

        btVenda.setText("Nova Venda");
        btVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendaActionPerformed(evt);
            }
        });

        mnHomeCad.setText("Cadastro");

        itMnCadFun.setText("Cadastrar Funcionário");
        itMnCadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFunActionPerformed(evt);
            }
        });
        mnHomeCad.add(itMnCadFun);

        itMnCadMat.setText("Cadastrar Material");

        itMnCadAlvenaria.setText("Alvenaria");
        itMnCadAlvenaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadAlvenariaActionPerformed(evt);
            }
        });
        itMnCadMat.add(itMnCadAlvenaria);

        itMnCadFerragens.setText("Ferragens");
        itMnCadFerragens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFerragensActionPerformed(evt);
            }
        });
        itMnCadMat.add(itMnCadFerragens);

        itMnCadCarpintaria.setText("Carpintaria");
        itMnCadCarpintaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadCarpintariaActionPerformed(evt);
            }
        });
        itMnCadMat.add(itMnCadCarpintaria);

        mnHomeCad.add(itMnCadMat);

        barMnHome.add(mnHomeCad);

        mnHomeRelat.setText("Relatório");

        itMnListClient.setText("Listar Clientes");
        itMnListClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnListClientActionPerformed(evt);
            }
        });
        mnHomeRelat.add(itMnListClient);

        itMnListFun.setText("Listar Funcionários");
        itMnListFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnListFunActionPerformed(evt);
            }
        });
        mnHomeRelat.add(itMnListFun);

        itMnListEstoque.setText("Listar Estoque");
        itMnListEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnListEstoqueActionPerformed(evt);
            }
        });
        mnHomeRelat.add(itMnListEstoque);

        itMnListVenda.setText("Listar Vendas");
        itMnListVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnListVendaActionPerformed(evt);
            }
        });
        mnHomeRelat.add(itMnListVenda);

        barMnHome.add(mnHomeRelat);

        mnHomeSist.setText("Sistema");

        itMnRemoProd.setText("Remover Produto");
        itMnRemoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRemoProdActionPerformed(evt);
            }
        });
        mnHomeSist.add(itMnRemoProd);

        itMnAttQuant.setText("Atualizar Quantidade");
        itMnAttQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnAttQuantActionPerformed(evt);
            }
        });
        mnHomeSist.add(itMnAttQuant);

        itMnSair.setText("Sair");
        itMnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnSairActionPerformed(evt);
            }
        });
        mnHomeSist.add(itMnSair);

        barMnHome.add(mnHomeSist);

        setJMenuBar(barMnHome);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCadCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVenda))
                    .addComponent(rtDepositoHome))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(rtDepositoHome)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadCliente)
                    .addComponent(btVenda))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMnCadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFunActionPerformed
        FormFuncionario.geraFormFuncionario().setVisible(true);
    }//GEN-LAST:event_itMnCadFunActionPerformed

    private void itMnCadAlvenariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadAlvenariaActionPerformed
        FormAlvenaria.geraFormAlvenaria().setVisible(true);
    }//GEN-LAST:event_itMnCadAlvenariaActionPerformed

    private void itMnCadFerragensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFerragensActionPerformed
        FormFerragens.geraFormFerragens().setVisible(true);
    }//GEN-LAST:event_itMnCadFerragensActionPerformed

    private void itMnCadCarpintariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadCarpintariaActionPerformed
        FormCarpintaria.geraFormCarpintaria().setVisible(true);
    }//GEN-LAST:event_itMnCadCarpintariaActionPerformed

    private void itMnListClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnListClientActionPerformed
        FormRelatorioClientes relClientes = FormRelatorioClientes.geraFormRelatorioClientes();
        relClientes.popularTabelaClientes();
        relClientes.setVisible(true);
    }//GEN-LAST:event_itMnListClientActionPerformed

    private void itMnListFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnListFunActionPerformed
        FormRelatorioFuncionarios relFuncionarios = FormRelatorioFuncionarios.geraFormRelatorioFuncionarios();
        relFuncionarios.popularTabelaFuncionarios();
        relFuncionarios.setVisible(true);
    }//GEN-LAST:event_itMnListFunActionPerformed

    private void itMnListEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnListEstoqueActionPerformed
        FormRelatorioEstoque relEstoque = FormRelatorioEstoque.geraFormRelatorioEstoque();
        relEstoque.popularTabelaEstoque();
        relEstoque.setVisible(true);
    }//GEN-LAST:event_itMnListEstoqueActionPerformed

    private void itMnListVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnListVendaActionPerformed
        FormRelatorioVendas relVendas = FormRelatorioVendas.geraFormRelatorioVendas();
        relVendas.popularTabelaVendas();
        relVendas.setVisible(true);
    }//GEN-LAST:event_itMnListVendaActionPerformed

    private void itMnRemoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRemoProdActionPerformed
        FormRemoverMaterial.geraFormRemoverMaterial().setVisible(true);
    }//GEN-LAST:event_itMnRemoProdActionPerformed

    private void itMnAttQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnAttQuantActionPerformed
        FormAtualizarQuantEstoque.geraFormAtualizarQuantEstoque().setVisible(true);
    }//GEN-LAST:event_itMnAttQuantActionPerformed

    private void itMnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnSairActionPerformed
        sairPrograma();
    }//GEN-LAST:event_itMnSairActionPerformed

    private void btCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadClienteActionPerformed
        FormCliente.geraFormCliente().setVisible(true);
    }//GEN-LAST:event_btCadClienteActionPerformed

    private void btVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendaActionPerformed
        FormVenda.geraFormVenda().setVisible(true);
    }//GEN-LAST:event_btVendaActionPerformed

    // Método para sair do programa
    public void sairPrograma() {
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair do sistema?",
                "Confirmação de Saída",
                JOptionPane.YES_NO_OPTION
        );
        if (resp == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMnHome;
    private javax.swing.JButton btCadCliente;
    private javax.swing.JButton btVenda;
    private javax.swing.JMenuItem itMnAttQuant;
    private javax.swing.JMenuItem itMnCadAlvenaria;
    private javax.swing.JMenuItem itMnCadCarpintaria;
    private javax.swing.JMenuItem itMnCadFerragens;
    private javax.swing.JMenuItem itMnCadFun;
    private javax.swing.JMenu itMnCadMat;
    private javax.swing.JMenuItem itMnListClient;
    private javax.swing.JMenuItem itMnListEstoque;
    private javax.swing.JMenuItem itMnListFun;
    private javax.swing.JMenuItem itMnListVenda;
    private javax.swing.JMenuItem itMnRemoProd;
    private javax.swing.JMenuItem itMnSair;
    private javax.swing.JMenu mnHomeCad;
    private javax.swing.JMenu mnHomeRelat;
    private javax.swing.JMenu mnHomeSist;
    private javax.swing.JLabel rtDepositoHome;
    // End of variables declaration//GEN-END:variables
}
