//Lucas Raphael, 2525518 - Mateus Rodrigues, 2503700 - Norberto Junior, 2209136

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Logger;
import java.util.ArrayList;

/**
 *
 * @author Mateus
 */
public class FormRelatorioEstoque extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(FormRelatorioEstoque.class.getName());

    //MÉTODO SINGLETON
    private static FormRelatorioEstoque formRelatorioEstoqueUnico;

    private BDEstoque bdEstoque = BDEstoque.geraBDEstoque();

    private FormRelatorioEstoque() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Depósito do Zé - Relatório de Estoque");
        
        popularTabelaEstoque(); 
    }

    //MÉTODO SINGLETON
    public static FormRelatorioEstoque geraFormRelatorioEstoque() {
        if (formRelatorioEstoqueUnico == null) {
            formRelatorioEstoqueUnico = new FormRelatorioEstoque();
        }
        return formRelatorioEstoqueUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEstoque = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        tabelaEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Código", "Valor", "Nome", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaEstoque);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSair))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sairForm();
    }//GEN-LAST:event_btSairActionPerformed

    public void popularTabelaEstoque() {
        DefaultTableModel modeloTabela = (DefaultTableModel) tabelaEstoque.getModel();
        modeloTabela.setRowCount(0);

        ArrayList<MateriaisModel> lista = bdEstoque.getListaMateriais();
        if (lista == null) {
            return;
        }

        for (MateriaisModel material : lista) {
            String tipoMaterial = "Desconhecido";

            if (material instanceof FerragensModel) {
                tipoMaterial = "Ferragens";
            } else if (material instanceof AlvenariaModel) {
                tipoMaterial = "Alvenaria";
            } else if (material instanceof CarpintariaModel) {
                tipoMaterial = "Carpintaria";
            }
            
            modeloTabela.addRow(new Object[]{
                material.getCodigo(),
                material.getNome(),
                material.getValor(),
                material.getQuantidade(),
                tipoMaterial
            });
        }
    }

    public void sairForm() {
        int resp = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente fechar o relatório de estoque?",
                "Saída",
                JOptionPane.YES_NO_OPTION
        );
        if (resp == JOptionPane.YES_OPTION) {
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaEstoque;
    // End of variables declaration//GEN-END:variables
}
